platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'FunGen' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end
